# Generated by Django 6.0.7 on 2026-07-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_address_shippingaddress_shipping_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_emial',
            new_name='shipping_email',
        ),
    ]
