# Generated by Django 6.0.7 on 2026-08-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_ordermodel_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='date_ship',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
